### PR TITLE
Streamline Intros

### PR DESCRIPTION
**Pull request by taroth21**
Trying to streamline the book intros like we did for SLE.

See: 
- https://github.com/SUSE/doc-sle/pull/778
- https://github.com/SUSE/doc-sle/pull/779
- https://github.com/SUSE/doc-sle/pull/780
- https://github.com/SUSE/doc-sle/pull/781

### CODE REVIEW

**Comment by taroth21** [comment]
@tomschr : I noticed that the lifecycle and support section of the intro  was missing here (maybe on purpose, because the support conditions for this product may differ from SLE?, maybe just because they had been added to the SLE intros more recently and this repo was not updated with doc-kit since then?). Not sure what to do, please advise. (Please note that the most recent intro changes are also still missing in doc-kit, need to create a PR there, too).

**Review by tomschr — COMMENTED** [review]
@taroth21 

> I noticed that the lifecycle and support section of the intro was missing here [...]
> Not sure what to do, please advise.

Hmn, missing? Are you sure? I can see that section in docserv for [SLES for SAP 15 SP3](http://docserv.suse.de/documents/en-us/sles-sap/15-SP3/html/SLES-SAP-guide/cha-about.html#id-1.4.9).

So it was even there before you've created your pull request. :slightly_smiling_face: Or do you mean something different?

> [...] and this repo was not updated with doc-kit since then

Stefan updated this repo some time ago (last change was in January 2021 in commit d61884c).

To be sure, I also rerun `doc-kit` some minutes ago. Git reported only minor changes in two common files (two changes in `<title>`). I've already pushed that into the `main` branch in commit f90e369.

So all in all, it looks good to me. If you agree, I can merge it to main.

**Comment by taroth21** [comment]
> @taroth21
> 
> > I noticed that the lifecycle and support section of the intro was missing here [...]
> > Not sure what to do, please advise.
> 
> Hmn, missing? Are you sure? I can see that section in docserv for [SLES for SAP 15 SP3](http://docserv.suse.de/documents/en-us/sles-sap/15-SP3/html/SLES-SAP-guide/cha-about.html#id-1.4.9).
> 
> So it was even there before you've created your pull request. slightly_smiling_face Or do you mean something different?

Ah, OK, it was included in a different chapter... sorry, I did not notice yesterday. I only checked the preface where this file is usually included. Is there a special reason why it is part of cha-about?
> 
> > [...] and this repo was not updated with doc-kit since then
> 
> Stefan updated this repo some time ago (last change was in January 2021 in commit [d61884c](https://github.com/SUSE/doc-slesforsap/commit/d61884cb8cf1233834041b16df50be25e1a44152)).
> 
> To be sure, I also rerun `doc-kit` some minutes ago. Git reported only minor changes in two common files (two changes in `<title>`). I've already pushed that into the `main` branch in commit [f90e369](https://github.com/SUSE/doc-slesforsap/commit/f90e3693663eb226271ec1584cd28a064d355d0a).

Yep, I noticed. It has overwritten my title change from yesterday (as I did not push that into doc-kit yet as mentioned)... but I can fix this. 
> 
> So all in all, it looks good to me. If you agree, I can merge it to main.

After clarifying/fixing the two issues above, I'm fine with merging.

**Comment by tomschr** [comment]
@taroth21 

> Ah, OK, it was included in a different chapter... sorry, I did not notice yesterday.

No problem. :slightly_smiling_face: 

> I only checked the preface where this file is usually included. Is there a special reason why it is part of cha-about?

No special reason. According to the log, Stefan added it in commit 711bc894. I left it as it is.

> > I've already pushed that into the main branch in commit f90e369.
>
> Yep, I noticed. It has overwritten my title change from yesterday (as I did not push that into doc-kit yet as mentioned)... but I can fix this.

Okay, ping me when you are ready. After your final approval I'll merge it.

Thanks Tanja!

**Comment by taroth21** [comment]
> @taroth21
> 
> > Ah, OK, it was included in a different chapter... sorry, I did not notice yesterday.
> 
> No problem. slightly_smiling_face
> 
> > I only checked the preface where this file is usually included. Is there a special reason why it is part of cha-about?
> 
> No special reason. According to the log, Stefan added it in commit [711bc89](https://github.com/SUSE/doc-slesforsap/commit/711bc894dcec7d4fd591145801d2d737d8554222). I left it as it is.

I see, probably because the chapter already contained specific Support information before. I have moved the support xinclude from chapter 1 to the preface now (to align with how we handle it for the rest of the SLE family).

If you are OK with this, we can merge.

**Comment by tomschr** [comment]
Thanks Tanja for your contributions! Much appreciated! :+1: 

I'll squash and merge it.

**Pull request merged**
