### PR TITLE
bsc#1181586 SLES15 SP2: ClamAV/ClamSAP allocates 1GB of anon memory segment for each SAP worker process     Fix 

### PR DESCRIPTION
**Pull request by varkoly**

### CODE REVIEW

**Comment by taroth21** [comment]
@varkoly : Thanks for updating the second screenshot, too! 
Latest PDF: 
[Uploading cha-clamsap_remarks_color_draft_en.pdf…]()

**Comment by varkoly** [comment]
This PR is needed for all supported SLES versions!

**Comment by taroth21** [comment]
@tomschr: After you are back, could you see to this please and backport the changes to the versions listed by Peter above? Many thanks!

**Comment by tomschr** [comment]
@taroth21 I already worked on a PR #51, but as the text and screenshots are now merged, I can close mine. :slightly_smiling_face: 

The backports are available in the maintenance branches now. I've commented it on my PR, see https://github.com/SUSE/doc-slesforsap/pull/51#issuecomment-792669398

**Pull request merged**
