### PR TITLE
Fix typo, thanks to Peter Varkoly

### PR DESCRIPTION
**Pull request by tomschr**
Found by Peter Varkoly. Many thanks! :+1: 

This PR contains:

* a typo fix

TODO:

* fix `images/src/jpg/sap-nw-scanner-definition-add.jpg`

Addition:

* Needs to be applied to SLE 12 SP2 an onwards

### CODE REVIEW

**Comment by stefanotorresi** [comment]
@tomschr I tried to fix the image by brutally editing it with Gimp, but since it's in low JPEG quality it didn't really work.
How can we help you?

**Comment by tomschr** [comment]
@stefanotorresi Thanks Stefano!
Do you know how difficult it is to shoot this screenshot? If it is easy, maybe it can be replicated. At the moment, I don't have access to a SAP system.

**Comment by lee-martin** [comment]
@tomschr  Can you confirm which SLE versions you will apply this update to? The documentation needs updating for everything from SLE 12 SP2 onwards, but it looks like this PR might only be in main (i.e. 15 SP3) - unless I'm just missing how to read this properly, in which case please tell me where to see which versions get the PR :)
thanks, lee

**Comment by stefanotorresi** [comment]
@tomschr I'm told by @varkoly that you should have both the updated screenshots now. Do you need anything else to fix the clamsap page?

**Comment by tomschr** [comment]
Hi @lee-martin 

> @tomschr Can you confirm which SLE versions you will apply this update to? The documentation needs updating for everything from SLE 12 SP2 onwards, but it looks like this PR might only be in main (i.e. 15 SP3) - unless I'm just missing how to read this properly, in which case please tell me where to see which versions get the PR :)

It's correct, this PR is targeted for the main/master branch and so for the latest SP. You're read this this PR correctly. 
In Git, you can only have a 1:1 relationship: one branch and one target. You can't merge a branch to multiple targets (in our case: multiple maintenance branches). At least not directly.

So yes, that's on purpose. :slightly_smiling_face: However, that doesn't mean the other maintenance branches are not worked on. 

I usually create a branch from main and submit a pull request. There I add all the changes, let it review from all stakeholders, and when the dust has been settled, I merge it to main. The commit(s) are then cherry-picked into the different maintenance branches.

Maybe I should have better mentioned that in the original description of the PR. I've updated the description.

Hope it makes sense. :slightly_smiling_face:

**Comment by tomschr** [comment]
@stefanotorresi 
> @tomschr I'm told by @varkoly that you should have both the updated screenshots now. Do you need anything else to fix the clamsap page?

Where are the updated screenshots? Did you send it by mail? I was away for a few days so I may have missed something.

**Comment by stefanotorresi** [comment]
> Where are the updated screenshots? Did you send it by mail? I was away for a few days so I may have missed something.

I have no clue... 😬 Could you please ask @varkoly directly?

**Comment by varkoly** [comment]
It is already done.
https://github.com/SUSE/doc-slesforsap/pull/55/files

Peter Varkoly
SW Engineering(Systems)

SUSE Software Solutions Germany GmbH
Maxfeldstr. 5
D-90409 Nürnberg

T +49-(0)911-740 53 0
E <varkoly@suse.com>

https://www.suse.com/

(HRB 36809, AG Nürnberg)
Geschäftsführer: Felix Imendörffer
________________________________
Von: Stefano Torresi <notifications@github.com>
Gesendet: Montag, 8. März 2021 09:36
An: SUSE/doc-slesforsap <doc-slesforsap@noreply.github.com>
Cc: Peter Varkoly <varkoly@suse.de>; Mention <mention@noreply.github.com>
Betreff: Re: [SUSE/doc-slesforsap] Fix typo, thanks to Peter Varkoly (#51)


Where are the updated screenshots? Did you send it by mail? I was away for a few days so I may have missed something.

I have no clue... 😬 Could you please ask @varkoly<https://github.com/varkoly> directly?

**Comment by tomschr** [comment]
@varkoly Ohh, I see. Thanks Peter! :+1:

**Comment by tomschr** [comment]
As far as I can see, this pull request can be closed as the issue is fixed in #55. The commits 7f259e0b and 871d562 needs to be cherry-picked to the maintenance branches.
Will do that.

**Comment by lee-martin** [comment]
> Hi @lee-martin
> 
> > @tomschr Can you confirm which SLE versions you will apply this update to? The documentation needs updating for everything from SLE 12 SP2 onwards, but it looks like this PR might only be in main (i.e. 15 SP3) - unless I'm just missing how to read this properly, in which case please tell me where to see which versions get the PR :)
> 
> It's correct, this PR is targeted for the main/master branch and so for the latest SP. You're read this this PR correctly.
> In Git, you can only have a 1:1 relationship: one branch and one target. You can't merge a branch to multiple targets (in our case: multiple maintenance branches). At least not directly.
> 
> So yes, that's on purpose. slightly_smiling_face However, that doesn't mean the other maintenance branches are not worked on.
> 
> I usually create a branch from main and submit a pull request. There I add all the changes, let it review from all stakeholders, and when the dust has been settled, I merge it to main. The commit(s) are then cherry-picked into the different maintenance branches.

@tomschr Thanks for your feedback, so can you take care of the changes/PRs necessary to port this change to all versions since  SLE 12 SP2  ?

**Comment by tomschr** [comment]
@lee-martin 
> @tomschr Thanks for your feedback, so can you take care of the changes/PRs necessary to port this change to all versions since SLE 12 SP2 ?

Yes, that was my plan. :slightly_smiling_face:

**Comment by tomschr** [comment]
Cherry-picked into different maintenance branches:

* `maintenance/12_SP2`: 7f6746b6 / d06efc024
* `maintenance/12_SP3`: da2b9d62 / 5ae3ef47
* `maintenance/12_SP4`: f77e14a / 1fd192f
* `maintenance/12_SP5`: f73a627 / acb8915
* `maintenance/15_GA`: 7b9ce07 / f28e5c0
* `maintenance/15_SP1`: 82c6073 / d5cc7c8
* `maintenance/15_SP2`: 6d6260e / 1d01906

Consider it as finished now, so closing.

**Pull request closed without merging**
