### PR TITLE
organizational changes

### PR DESCRIPTION
**Pull request by sknorr**
* include new support intro from doc-kit and move existing lifecycle section into it (should be backported to 15 SP1/15 GA)
* remove SLE 12-era module/extension description and replace with link to SLES Modules guide (should be backported to 15 SP1/15 GA)
* rename DC files to the official short product name (should not be backported)
* remove -s4s- component from IDs (may be a bit controversial, not sure whether now is a good time for it; and should not be backported)

### CODE REVIEW

**Comment by tomschr** [comment]
@sknorr Wow, thanks for your contribution! :+1: 

I only have one remark/question for this point:

> remove -s4s- component from IDs (may be a bit controversial, not sure whether now is a good time for it; and should not be backported)

Hmn... :thinking: ... good question. I would probably prefer to add such a change _after_ the release. Maybe we need to cherry-pick something which would cause headaches. Having ID changes after the release avoids this problem. Would that make sense?

Furthermore, the CI reports this error:

```
/usr/src/app/build/.profiled/noquick_sles/common_intro_support.xml:11:45:
 warning: Include operation failed, reverting to fallback. 
Resource error reading file as XML (href='common_intro_cycle.xml').
Reason: /usr/src/app/build/.profiled/noquick_sles/common_intro_cycle.xml 
 (No such file or directory)
/usr/src/app/build/.profiled/noquick_sles/MAIN-SLES4SAP-guide.xml:25:51: 
  fatal: Error attempting to parse XML file (href='s4s_overview.xml').
```

I assume you will fix that. :smiley:

**Comment by sknorr** [comment]
>Furthermore, the CI reports this error

Ah, damn it :/ I should really have validated both DC files. Sorry for my stupid.

>I would probably prefer to add such a change after the release. Maybe we need to cherry-pick something which would cause headaches. Having ID changes after the release avoids this problem. Would that make sense?

Since you'll have to continue to cherry-pick to older branches that don't have this change for 5 or so years, this will remain problematic, no matter how/when it's merged.

**Comment by sknorr** [comment]
CI error should be fixed now -- I forgot to `git add` a file originally.

**Comment by tomschr** [comment]
> > Furthermore, the CI reports this error
> 
> Ah, damn it :/ I should really have validated both DC files. Sorry for my stupid.

Na, no worries. :-) Thanks for the fixes! :+1: 


> [...]
> Since you'll have to continue to cherry-pick to older branches that don't have this change for 5 or so years, this will remain problematic, no matter how/when it's merged. I just thought that since proofing was happening right now, it might more problematic currently.

Yeah, maybe it doesn't that matter anyway. 

Thanks!

**Pull request merged**
